name: Static code analysis including build test and memory check

on:
  push

jobs:
  build_and_test:
    runs-on: ubuntu-latest
	container: amdbike/mosze:latest
    steps:
      - uses: actions/checkout@v2 
      - name: Run code analysis with cppcheck
        run: make sca
      - name: Upload Cppcheck result 
        uses: actions/upload-artifact@v2  
        with:
          name: cppcheck_output
          path: cppcheck_output.txt
      - name: Run static code analysis test
        run: make sca-test