name: Test workflow

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: chmod +x ./test.sh
      - run: g++ -Wall main.cpp Character.cpp Player.cpp
      - run: ./test.sh