name: Test workflow

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: chmod 755 main.cpp Character.cpp Character.h units/Vader.json units/Luke.json units/Yoda.json
      - run: chmod +x test.sh
      - run: g++ -Wall main.cpp Character.cpp
      - run: ./test.sh