name: Unit tests

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install GoogleTest
      - run: sudo apt install libgtest-dev
      - name: Install CMake
      - run: sudo apt isntall cmake
      - name: Direct you in to the righ folder
      - run: cd /usr/src/gtest
      - name: Create CMake.txt
      - run: sudo cmake CMakeLists.txt
      - name: Build the test
      - run: sudo make
      - name: Create references
      - run: sudo ln -st /usr/lib/ /usr/src/gtest/libgtest.a
      - run: sudo ln -st /usr/lib/ /usr/src/gtest/libgtest_main.a
	  - name: Build
      - run: g++ -std=c++17 *.cpp
      - name: Run the test
      - run: test/UnitTest